/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPredictionMarketOriginal,
  IPredictionMarketOriginalInterface,
} from "../../helperContract.sol/IPredictionMarketOriginal";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "marketId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "userInvestments",
    outputs: [
      {
        internalType: "uint256",
        name: "totalInvested",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lastUpdated",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPredictionMarketOriginal__factory {
  static readonly abi = _abi;
  static createInterface(): IPredictionMarketOriginalInterface {
    return new Interface(_abi) as IPredictionMarketOriginalInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPredictionMarketOriginal {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPredictionMarketOriginal;
  }
}
