/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPDX } from "./IPDX";
export type { IPDXPredictionMarketOwnership } from "./IPDXPredictionMarketOwnership";
export type { MarketMarketplace } from "./MarketMarketplace";
