/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPredictionMarket } from "./IPredictionMarket";
export type { OutcomeToken } from "./OutcomeToken";
export type { PredictionMarketWithMultipliers } from "./PredictionMarketWithMultipliers";
export type { TradingBot } from "./TradingBot";
