/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TestnetDualTokenAdapterResolutionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canDispute"
      | "canRequestResolution"
      | "claimPDXRedemption"
      | "disputeResolution"
      | "getDisputeDeadline"
      | "getMarketOutcome"
      | "getResolution"
      | "getResolutionStatus"
      | "mainAdapter"
      | "requestResolution"
      | "resolutionStates"
      | "resolveDisputedMarket"
      | "resolveMarket"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeResolved"
      | "MarketResolved"
      | "RedemptionClaimed"
      | "ResolutionDisputed"
      | "ResolutionRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "canDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canRequestResolution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimPDXRedemption",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeResolution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDisputeDeadline",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketOutcome",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getResolution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getResolutionStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mainAdapter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestResolution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolutionStates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDisputedMarket",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMarket",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "canDispute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "canRequestResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimPDXRedemption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDisputeDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketOutcome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResolutionStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mainAdapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolutionStates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDisputedMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarket",
    data: BytesLike
  ): Result;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    finalOutcome: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    finalOutcome: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    finalOutcome: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    outcome: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    outcome: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    outcome: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionClaimedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    user: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    user: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolutionDisputedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    disputer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    disputer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    disputer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolutionRequestedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    requester: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    requester: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    requester: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TestnetDualTokenAdapterResolution extends BaseContract {
  connect(runner?: ContractRunner | null): TestnetDualTokenAdapterResolution;
  waitForDeployment(): Promise<this>;

  interface: TestnetDualTokenAdapterResolutionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canDispute: TypedContractMethod<[marketId: BigNumberish], [boolean], "view">;

  canRequestResolution: TypedContractMethod<
    [marketId: BigNumberish],
    [boolean],
    "view"
  >;

  claimPDXRedemption: TypedContractMethod<
    [marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  disputeResolution: TypedContractMethod<
    [marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getDisputeDeadline: TypedContractMethod<
    [marketId: BigNumberish],
    [bigint],
    "view"
  >;

  getMarketOutcome: TypedContractMethod<
    [marketId: BigNumberish],
    [boolean],
    "view"
  >;

  getResolution: TypedContractMethod<
    [marketId: BigNumberish],
    [
      [boolean, bigint, string, boolean, bigint, string, boolean, boolean] & {
        requested: boolean;
        requestTime: bigint;
        requester: string;
        disputed: boolean;
        disputeTime: bigint;
        disputer: string;
        resolved: boolean;
        outcome: boolean;
      }
    ],
    "view"
  >;

  getResolutionStatus: TypedContractMethod<
    [marketId: BigNumberish],
    [string],
    "view"
  >;

  mainAdapter: TypedContractMethod<[], [string], "view">;

  requestResolution: TypedContractMethod<
    [marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  resolutionStates: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [boolean, bigint, string, boolean, bigint, string, boolean, boolean] & {
        requested: boolean;
        requestTime: bigint;
        requester: string;
        disputed: boolean;
        disputeTime: bigint;
        disputer: string;
        resolved: boolean;
        outcome: boolean;
      }
    ],
    "view"
  >;

  resolveDisputedMarket: TypedContractMethod<
    [marketId: BigNumberish, finalOutcome: boolean],
    [void],
    "nonpayable"
  >;

  resolveMarket: TypedContractMethod<
    [marketId: BigNumberish, outcome: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canDispute"
  ): TypedContractMethod<[marketId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "canRequestResolution"
  ): TypedContractMethod<[marketId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "claimPDXRedemption"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "disputeResolution"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDisputeDeadline"
  ): TypedContractMethod<[marketId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMarketOutcome"
  ): TypedContractMethod<[marketId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getResolution"
  ): TypedContractMethod<
    [marketId: BigNumberish],
    [
      [boolean, bigint, string, boolean, bigint, string, boolean, boolean] & {
        requested: boolean;
        requestTime: bigint;
        requester: string;
        disputed: boolean;
        disputeTime: bigint;
        disputer: string;
        resolved: boolean;
        outcome: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getResolutionStatus"
  ): TypedContractMethod<[marketId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "mainAdapter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestResolution"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolutionStates"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [boolean, bigint, string, boolean, bigint, string, boolean, boolean] & {
        requested: boolean;
        requestTime: bigint;
        requester: string;
        disputed: boolean;
        disputeTime: bigint;
        disputer: string;
        resolved: boolean;
        outcome: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "resolveDisputedMarket"
  ): TypedContractMethod<
    [marketId: BigNumberish, finalOutcome: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveMarket"
  ): TypedContractMethod<
    [marketId: BigNumberish, outcome: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionClaimed"
  ): TypedContractEvent<
    RedemptionClaimedEvent.InputTuple,
    RedemptionClaimedEvent.OutputTuple,
    RedemptionClaimedEvent.OutputObject
  >;
  getEvent(
    key: "ResolutionDisputed"
  ): TypedContractEvent<
    ResolutionDisputedEvent.InputTuple,
    ResolutionDisputedEvent.OutputTuple,
    ResolutionDisputedEvent.OutputObject
  >;
  getEvent(
    key: "ResolutionRequested"
  ): TypedContractEvent<
    ResolutionRequestedEvent.InputTuple,
    ResolutionRequestedEvent.OutputTuple,
    ResolutionRequestedEvent.OutputObject
  >;

  filters: {
    "DisputeResolved(uint256,bool,uint256)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "MarketResolved(uint256,bool,uint256)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;

    "RedemptionClaimed(uint256,address,uint256,uint256)": TypedContractEvent<
      RedemptionClaimedEvent.InputTuple,
      RedemptionClaimedEvent.OutputTuple,
      RedemptionClaimedEvent.OutputObject
    >;
    RedemptionClaimed: TypedContractEvent<
      RedemptionClaimedEvent.InputTuple,
      RedemptionClaimedEvent.OutputTuple,
      RedemptionClaimedEvent.OutputObject
    >;

    "ResolutionDisputed(uint256,address,uint256)": TypedContractEvent<
      ResolutionDisputedEvent.InputTuple,
      ResolutionDisputedEvent.OutputTuple,
      ResolutionDisputedEvent.OutputObject
    >;
    ResolutionDisputed: TypedContractEvent<
      ResolutionDisputedEvent.InputTuple,
      ResolutionDisputedEvent.OutputTuple,
      ResolutionDisputedEvent.OutputObject
    >;

    "ResolutionRequested(uint256,address,uint256)": TypedContractEvent<
      ResolutionRequestedEvent.InputTuple,
      ResolutionRequestedEvent.OutputTuple,
      ResolutionRequestedEvent.OutputObject
    >;
    ResolutionRequested: TypedContractEvent<
      ResolutionRequestedEvent.InputTuple,
      ResolutionRequestedEvent.OutputTuple,
      ResolutionRequestedEvent.OutputObject
    >;
  };
}
