/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPredictionMarket } from "./IPredictionMarket";
export type { MarketFactory } from "./MarketFactory";
