/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMainAdapter__factory } from "./IMainAdapter__factory";
export { IOutcomeToken__factory } from "./IOutcomeToken__factory";
export { IPDX__factory } from "./IPDX__factory";
export { TestnetDualTokenAdapterResolution__factory } from "./TestnetDualTokenAdapterResolution__factory";
