/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PredictionMarketWithMultipliersInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DISPUTE_PERIOD"
      | "MINIMUM_LIQUIDITY"
      | "MIN_INITIAL_LIQUIDITY"
      | "addLiquidity"
      | "buyNoWithBNB"
      | "buyYesWithBNB"
      | "claimRedemption"
      | "createMarket"
      | "feeBps"
      | "formatMultiplier"
      | "getAllMarkets"
      | "getBuyNoMultiplier"
      | "getBuyNoOutput"
      | "getBuyYesMultiplier"
      | "getBuyYesOutput"
      | "getCurrentMultipliers"
      | "getMarket"
      | "getSwapMultiplier"
      | "getTradingInfo"
      | "getUserInvestment"
      | "getUserTotalInvestment"
      | "lpBalances"
      | "lpFeeBps"
      | "markets"
      | "nextMarketId"
      | "owner"
      | "removeLiquidity"
      | "requestResolution"
      | "resolutionServer"
      | "resolveMarket"
      | "swapNoForYes"
      | "swapYesForNo"
      | "userInvestments"
      | "withdrawPlatformFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BuyWithBNB"
      | "LiquidityAdded"
      | "LiquidityRemoved"
      | "MarketCreated"
      | "MarketResolved"
      | "RedemptionClaimed"
      | "ResolutionRequested"
      | "Swap"
      | "UserInvestmentUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DISPUTE_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MINIMUM_LIQUIDITY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_INITIAL_LIQUIDITY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyNoWithBNB",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buyYesWithBNB",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRedemption",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarket",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "feeBps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "formatMultiplier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllMarkets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyNoMultiplier",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyNoOutput",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyYesMultiplier",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyYesOutput",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentMultipliers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSwapMultiplier",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getTradingInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserInvestment",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTotalInvestment",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lpBalances",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "lpFeeBps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "markets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextMarketId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestResolution",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "resolutionServer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMarket",
    values: [BigNumberish, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapNoForYes",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapYesForNo",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userInvestments",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPlatformFees",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DISPUTE_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MINIMUM_LIQUIDITY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_INITIAL_LIQUIDITY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyNoWithBNB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyYesWithBNB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRedemption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "formatMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllMarkets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyNoMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyNoOutput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyYesMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyYesOutput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentMultipliers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMarket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSwapMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTradingInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserInvestment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTotalInvestment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lpBalances", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lpFeeBps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextMarketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolutionServer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapNoForYes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapYesForNo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userInvestments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPlatformFees",
    data: BytesLike
  ): Result;
}

export namespace BuyWithBNBEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    buyYes: boolean,
    bnbIn: BigNumberish,
    tokenOut: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    user: string,
    buyYes: boolean,
    bnbIn: bigint,
    tokenOut: bigint
  ];
  export interface OutputObject {
    id: bigint;
    user: string;
    buyYes: boolean;
    bnbIn: bigint;
    tokenOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityAddedEvent {
  export type InputTuple = [
    id: BigNumberish,
    provider: AddressLike,
    yesAmount: BigNumberish,
    noAmount: BigNumberish,
    lpTokens: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    provider: string,
    yesAmount: bigint,
    noAmount: bigint,
    lpTokens: bigint
  ];
  export interface OutputObject {
    id: bigint;
    provider: string;
    yesAmount: bigint;
    noAmount: bigint;
    lpTokens: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityRemovedEvent {
  export type InputTuple = [
    id: BigNumberish,
    provider: AddressLike,
    yesAmount: BigNumberish,
    noAmount: BigNumberish,
    lpTokens: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    provider: string,
    yesAmount: bigint,
    noAmount: bigint,
    lpTokens: bigint
  ];
  export interface OutputObject {
    id: bigint;
    provider: string;
    yesAmount: bigint;
    noAmount: bigint;
    lpTokens: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    question: string,
    category: string,
    yesToken: AddressLike,
    noToken: AddressLike,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    question: string,
    category: string,
    yesToken: string,
    noToken: string,
    endTime: bigint
  ];
  export interface OutputObject {
    id: bigint;
    question: string;
    category: string;
    yesToken: string;
    noToken: string;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [
    id: BigNumberish,
    outcome: BigNumberish,
    reason: string,
    confidence: BigNumberish,
    resolvedBy: AddressLike
  ];
  export type OutputTuple = [
    id: bigint,
    outcome: bigint,
    reason: string,
    confidence: bigint,
    resolvedBy: string
  ];
  export interface OutputObject {
    id: bigint;
    outcome: bigint;
    reason: string;
    confidence: bigint;
    resolvedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionClaimedEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    amountClaimed: BigNumberish
  ];
  export type OutputTuple = [id: bigint, user: string, amountClaimed: bigint];
  export interface OutputObject {
    id: bigint;
    user: string;
    amountClaimed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolutionRequestedEvent {
  export type InputTuple = [
    id: BigNumberish,
    requester: AddressLike,
    requestedAt: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    requester: string,
    requestedAt: bigint
  ];
  export interface OutputObject {
    id: bigint;
    requester: string;
    requestedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    yesIn: boolean,
    amountIn: BigNumberish,
    amountOut: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    user: string,
    yesIn: boolean,
    amountIn: bigint,
    amountOut: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    id: bigint;
    user: string;
    yesIn: boolean;
    amountIn: bigint;
    amountOut: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserInvestmentUpdatedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    user: AddressLike,
    totalInvested: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    user: string,
    totalInvested: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    user: string;
    totalInvested: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionMarketWithMultipliers extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarketWithMultipliers;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketWithMultipliersInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DISPUTE_PERIOD: TypedContractMethod<[], [bigint], "view">;

  MINIMUM_LIQUIDITY: TypedContractMethod<[], [bigint], "view">;

  MIN_INITIAL_LIQUIDITY: TypedContractMethod<[], [bigint], "view">;

  addLiquidity: TypedContractMethod<
    [id: BigNumberish, yesAmount: BigNumberish, noAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  buyNoWithBNB: TypedContractMethod<
    [id: BigNumberish, minNoOut: BigNumberish],
    [void],
    "payable"
  >;

  buyYesWithBNB: TypedContractMethod<
    [id: BigNumberish, minYesOut: BigNumberish],
    [void],
    "payable"
  >;

  claimRedemption: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  createMarket: TypedContractMethod<
    [
      question: string,
      category: string,
      endTime: BigNumberish,
      initialYes: BigNumberish,
      initialNo: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  feeBps: TypedContractMethod<[], [bigint], "view">;

  formatMultiplier: TypedContractMethod<
    [multiplier: BigNumberish],
    [string],
    "view"
  >;

  getAllMarkets: TypedContractMethod<[], [bigint], "view">;

  getBuyNoMultiplier: TypedContractMethod<
    [id: BigNumberish, bnbAmount: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        multiplier: bigint;
        totalNoOut: bigint;
        totalFee: bigint;
      }
    ],
    "view"
  >;

  getBuyNoOutput: TypedContractMethod<
    [id: BigNumberish, bnbAmount: BigNumberish],
    [[bigint, bigint] & { totalNoOut: bigint; totalFee: bigint }],
    "view"
  >;

  getBuyYesMultiplier: TypedContractMethod<
    [id: BigNumberish, bnbAmount: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        multiplier: bigint;
        totalYesOut: bigint;
        totalFee: bigint;
      }
    ],
    "view"
  >;

  getBuyYesOutput: TypedContractMethod<
    [id: BigNumberish, bnbAmount: BigNumberish],
    [[bigint, bigint] & { totalYesOut: bigint; totalFee: bigint }],
    "view"
  >;

  getCurrentMultipliers: TypedContractMethod<
    [id: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        yesMultiplier: bigint;
        noMultiplier: bigint;
        yesPrice: bigint;
        noPrice: bigint;
      }
    ],
    "view"
  >;

  getMarket: TypedContractMethod<
    [id: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        creator: string;
        question: string;
        category: string;
        endTime: bigint;
        status: bigint;
        outcome: bigint;
        yesPool: bigint;
        noPool: bigint;
        totalBacking: bigint;
      }
    ],
    "view"
  >;

  getSwapMultiplier: TypedContractMethod<
    [id: BigNumberish, amountIn: BigNumberish, yesIn: boolean],
    [
      [bigint, bigint, bigint] & {
        multiplier: bigint;
        amountOut: bigint;
        fee: bigint;
      }
    ],
    "view"
  >;

  getTradingInfo: TypedContractMethod<
    [id: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        yesMultiplier: bigint;
        noMultiplier: bigint;
        yesPrice: bigint;
        noPrice: bigint;
        totalLiquidity: bigint;
      }
    ],
    "view"
  >;

  getUserInvestment: TypedContractMethod<
    [marketId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;

  getUserTotalInvestment: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  lpBalances: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  lpFeeBps: TypedContractMethod<[], [bigint], "view">;

  markets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        string,
        string
      ] & {
        creator: string;
        question: string;
        category: string;
        endTime: bigint;
        status: bigint;
        outcome: bigint;
        yesToken: string;
        noToken: string;
        yesPool: bigint;
        noPool: bigint;
        lpTotalSupply: bigint;
        totalBacking: bigint;
        platformFees: bigint;
        resolutionRequestedAt: bigint;
        resolutionRequester: string;
        resolutionReason: string;
        resolutionConfidence: bigint;
        disputeDeadline: bigint;
        disputer: string;
        disputeReason: string;
      }
    ],
    "view"
  >;

  nextMarketId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  removeLiquidity: TypedContractMethod<
    [id: BigNumberish, lpAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  requestResolution: TypedContractMethod<
    [id: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  resolutionServer: TypedContractMethod<[], [string], "view">;

  resolveMarket: TypedContractMethod<
    [
      id: BigNumberish,
      outcomeIndex: BigNumberish,
      reason: string,
      confidence: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  swapNoForYes: TypedContractMethod<
    [id: BigNumberish, noIn: BigNumberish, minYesOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  swapYesForNo: TypedContractMethod<
    [id: BigNumberish, yesIn: BigNumberish, minNoOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  userInvestments: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [[bigint, bigint] & { totalInvested: bigint; lastUpdated: bigint }],
    "view"
  >;

  withdrawPlatformFees: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DISPUTE_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MINIMUM_LIQUIDITY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_INITIAL_LIQUIDITY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<
    [id: BigNumberish, yesAmount: BigNumberish, noAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "buyNoWithBNB"
  ): TypedContractMethod<
    [id: BigNumberish, minNoOut: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "buyYesWithBNB"
  ): TypedContractMethod<
    [id: BigNumberish, minYesOut: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "claimRedemption"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [
      question: string,
      category: string,
      endTime: BigNumberish,
      initialYes: BigNumberish,
      initialNo: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "feeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "formatMultiplier"
  ): TypedContractMethod<[multiplier: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getAllMarkets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBuyNoMultiplier"
  ): TypedContractMethod<
    [id: BigNumberish, bnbAmount: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        multiplier: bigint;
        totalNoOut: bigint;
        totalFee: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBuyNoOutput"
  ): TypedContractMethod<
    [id: BigNumberish, bnbAmount: BigNumberish],
    [[bigint, bigint] & { totalNoOut: bigint; totalFee: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBuyYesMultiplier"
  ): TypedContractMethod<
    [id: BigNumberish, bnbAmount: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        multiplier: bigint;
        totalYesOut: bigint;
        totalFee: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBuyYesOutput"
  ): TypedContractMethod<
    [id: BigNumberish, bnbAmount: BigNumberish],
    [[bigint, bigint] & { totalYesOut: bigint; totalFee: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentMultipliers"
  ): TypedContractMethod<
    [id: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        yesMultiplier: bigint;
        noMultiplier: bigint;
        yesPrice: bigint;
        noPrice: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarket"
  ): TypedContractMethod<
    [id: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        creator: string;
        question: string;
        category: string;
        endTime: bigint;
        status: bigint;
        outcome: bigint;
        yesPool: bigint;
        noPool: bigint;
        totalBacking: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSwapMultiplier"
  ): TypedContractMethod<
    [id: BigNumberish, amountIn: BigNumberish, yesIn: boolean],
    [
      [bigint, bigint, bigint] & {
        multiplier: bigint;
        amountOut: bigint;
        fee: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTradingInfo"
  ): TypedContractMethod<
    [id: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        yesMultiplier: bigint;
        noMultiplier: bigint;
        yesPrice: bigint;
        noPrice: bigint;
        totalLiquidity: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserInvestment"
  ): TypedContractMethod<
    [marketId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserTotalInvestment"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lpBalances"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "lpFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        string,
        string
      ] & {
        creator: string;
        question: string;
        category: string;
        endTime: bigint;
        status: bigint;
        outcome: bigint;
        yesToken: string;
        noToken: string;
        yesPool: bigint;
        noPool: bigint;
        lpTotalSupply: bigint;
        totalBacking: bigint;
        platformFees: bigint;
        resolutionRequestedAt: bigint;
        resolutionRequester: string;
        resolutionReason: string;
        resolutionConfidence: bigint;
        disputeDeadline: bigint;
        disputer: string;
        disputeReason: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextMarketId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeLiquidity"
  ): TypedContractMethod<
    [id: BigNumberish, lpAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestResolution"
  ): TypedContractMethod<
    [id: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolutionServer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resolveMarket"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      outcomeIndex: BigNumberish,
      reason: string,
      confidence: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapNoForYes"
  ): TypedContractMethod<
    [id: BigNumberish, noIn: BigNumberish, minYesOut: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapYesForNo"
  ): TypedContractMethod<
    [id: BigNumberish, yesIn: BigNumberish, minNoOut: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userInvestments"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [[bigint, bigint] & { totalInvested: bigint; lastUpdated: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawPlatformFees"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BuyWithBNB"
  ): TypedContractEvent<
    BuyWithBNBEvent.InputTuple,
    BuyWithBNBEvent.OutputTuple,
    BuyWithBNBEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityAdded"
  ): TypedContractEvent<
    LiquidityAddedEvent.InputTuple,
    LiquidityAddedEvent.OutputTuple,
    LiquidityAddedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityRemoved"
  ): TypedContractEvent<
    LiquidityRemovedEvent.InputTuple,
    LiquidityRemovedEvent.OutputTuple,
    LiquidityRemovedEvent.OutputObject
  >;
  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionClaimed"
  ): TypedContractEvent<
    RedemptionClaimedEvent.InputTuple,
    RedemptionClaimedEvent.OutputTuple,
    RedemptionClaimedEvent.OutputObject
  >;
  getEvent(
    key: "ResolutionRequested"
  ): TypedContractEvent<
    ResolutionRequestedEvent.InputTuple,
    ResolutionRequestedEvent.OutputTuple,
    ResolutionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "Swap"
  ): TypedContractEvent<
    SwapEvent.InputTuple,
    SwapEvent.OutputTuple,
    SwapEvent.OutputObject
  >;
  getEvent(
    key: "UserInvestmentUpdated"
  ): TypedContractEvent<
    UserInvestmentUpdatedEvent.InputTuple,
    UserInvestmentUpdatedEvent.OutputTuple,
    UserInvestmentUpdatedEvent.OutputObject
  >;

  filters: {
    "BuyWithBNB(uint256,address,bool,uint256,uint256)": TypedContractEvent<
      BuyWithBNBEvent.InputTuple,
      BuyWithBNBEvent.OutputTuple,
      BuyWithBNBEvent.OutputObject
    >;
    BuyWithBNB: TypedContractEvent<
      BuyWithBNBEvent.InputTuple,
      BuyWithBNBEvent.OutputTuple,
      BuyWithBNBEvent.OutputObject
    >;

    "LiquidityAdded(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;
    LiquidityAdded: TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;

    "LiquidityRemoved(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;
    LiquidityRemoved: TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;

    "MarketCreated(uint256,string,string,address,address,uint256)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MarketResolved(uint256,uint8,string,uint256,address)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;

    "RedemptionClaimed(uint256,address,uint256)": TypedContractEvent<
      RedemptionClaimedEvent.InputTuple,
      RedemptionClaimedEvent.OutputTuple,
      RedemptionClaimedEvent.OutputObject
    >;
    RedemptionClaimed: TypedContractEvent<
      RedemptionClaimedEvent.InputTuple,
      RedemptionClaimedEvent.OutputTuple,
      RedemptionClaimedEvent.OutputObject
    >;

    "ResolutionRequested(uint256,address,uint256)": TypedContractEvent<
      ResolutionRequestedEvent.InputTuple,
      ResolutionRequestedEvent.OutputTuple,
      ResolutionRequestedEvent.OutputObject
    >;
    ResolutionRequested: TypedContractEvent<
      ResolutionRequestedEvent.InputTuple,
      ResolutionRequestedEvent.OutputTuple,
      ResolutionRequestedEvent.OutputObject
    >;

    "Swap(uint256,address,bool,uint256,uint256,uint256)": TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;
    Swap: TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;

    "UserInvestmentUpdated(uint256,address,uint256,uint256)": TypedContractEvent<
      UserInvestmentUpdatedEvent.InputTuple,
      UserInvestmentUpdatedEvent.OutputTuple,
      UserInvestmentUpdatedEvent.OutputObject
    >;
    UserInvestmentUpdated: TypedContractEvent<
      UserInvestmentUpdatedEvent.InputTuple,
      UserInvestmentUpdatedEvent.OutputTuple,
      UserInvestmentUpdatedEvent.OutputObject
    >;
  };
}
