/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BNBCustodialMarketplace } from "./BNBCustodialMarketplace";
export type { IPredictionMarket } from "./IPredictionMarket";
