/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPDXPredictionMarketCore,
  IPDXPredictionMarketCoreInterface,
} from "../../../contracts/PDXhelperContract.sol/IPDXPredictionMarketCore";

const _abi = [
  {
    inputs: [],
    name: "feeBps",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lpFeeBps",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "markets",
    outputs: [
      {
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        internalType: "string",
        name: "question",
        type: "string",
      },
      {
        internalType: "string",
        name: "category",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "endTime",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "status",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "outcome",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "yesToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "noToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "yesPool",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "noPool",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalBacking",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "platformFees",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "resolutionRequestedAt",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "resolutionRequester",
        type: "address",
      },
      {
        internalType: "string",
        name: "resolutionReason",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "resolutionConfidence",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "disputeDeadline",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "disputer",
        type: "address",
      },
      {
        internalType: "string",
        name: "disputeReason",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nextMarketId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "marketId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "userInvestments",
    outputs: [
      {
        internalType: "uint256",
        name: "totalInvested",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lastUpdated",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPDXPredictionMarketCore__factory {
  static readonly abi = _abi;
  static createInterface(): IPDXPredictionMarketCoreInterface {
    return new Interface(_abi) as IPDXPredictionMarketCoreInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPDXPredictionMarketCore {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPDXPredictionMarketCore;
  }
}
